name: Build Emulators (Box64)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_box64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup NDK r26d
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d

      - name: Build Box64 Android
        run: |
          git clone --depth 1 --branch v0.4.0 https://github.com/ptitSeb/box64.git
          mkdir box64/build && cd box64/build
          
          cmake .. \
            -DARM64=ON \
            -DANDROID=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-35
          
          make -j$(nproc)
          
          mkdir -p ../output
          cp box64 ../output/box64-android
          echo "Box64 Build Done"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: box64-android
          path: output/box64-android
